name: DDOSPrototype
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.2
  settings:
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGN_IDENTITY: ""
    PROVISIONING_PROFILE_SPECIFIER: ""
targets:
  DDOSPrototype:
    type: application
    platform: iOS
    sources: [DDOSPrototype]
    dependencies:
      - target: DDoSLiveActivityWidget
    info:
      path: DDOSPrototype/Info.plist
      properties:
        CFBundleDisplayName: DDOSPrototype
        UILaunchScreen: ~
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        NSSupportsLiveActivities: true
        NSSupportsLiveActivitiesFrequentUpdates: true
    settings:
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      PROVISIONING_PROFILE_SPECIFIER: ""
      VALIDATE_EMBEDDED_BINARY: NO
      CODE_SIGNING_REQUIRED: NO
  DDoSLiveActivityWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: DDoSLiveActivityWidget
      - path: DDOSPrototype/LiveActivityAttributes.swift
      - path: DDOSPrototype/AppIntent.swift
    info:
      path: DDoSLiveActivityWidget/Info.plist
      properties:
        CFBundleDisplayName: DDoSLiveActivityWidget
        CFBundleIdentifier: com.example.DDOSPrototype.widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.DDOSPrototype.widget
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      PROVISIONING_PROFILE_SPECIFIER: ""
      CODE_SIGNING_REQUIRED: NO
