name: DDOSPrototype
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.2
targets:
  DDOSPrototype:
    type: application
    platform: iOS
    sources: [DDOSPrototype]
    dependencies:
      - target: DDoSLiveActivityWidget
    info:
      path: DDOSPrototype/Info.plist
      properties:
        CFBundleDisplayName: DDOSPrototype
        UILaunchScreen: ~
        NSSupportsLiveActivities: true
        NSSupportsLiveActivitiesFrequentUpdates: true
  DDoSLiveActivityWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: DDoSLiveActivityWidget
      - path: DDOSPrototype/LiveActivityAttributes.swift
      - path: DDOSPrototype/AppIntent.swift
    info:
      path: DDoSLiveActivityWidget/Info.plist
      properties:
        CFBundleDisplayName: DDoSLiveActivityWidget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
